// src/pages/Home.tsx

import React, { useState, useEffect } from "react"; // Added React for JSX
import { toast } from "@/components/ui/sonner";
import Header from "@/components/Header";
import AuthForm from "@/components/AuthForm";
import FamilyTreeForm from "@/components/FamilyTreeForm";
import FamilyTreeDisplay from "@/components/FamilyTreeDisplay"; // Your LATEST persona-node version
import Footer from "@/components/Footer";
import { TreeFormData, FamilyTree, FamilyMember } from "@/types";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/context/AuthContext";
import { Button } from "@/components/ui/button";
import { Dna, Users, FileText, Search, Eye, Save, ZoomIn, ZoomOut } from "lucide-react"; // Added Zoom icons
import { useNavigate } from "react-router-dom";

const Home = () => {
  const { user, session } = useAuth(); // Assuming session is available from useAuth for token
  const [showAuth, setShowAuth] = useState<boolean>(false);
  const [isLoading, setIsLoading] = useState<boolean>(false); // For AI generation + saving
  const [familyTreeForPreview, setFamilyTreeForPreview] = useState<FamilyTree | null>(null);
  const [previewZoomLevel, setPreviewZoomLevel] = useState<number>(0.6); // Initial zoom for preview
  const navigate = useNavigate();

  useEffect(() => {
    // If user logs out while a tree is displayed for preview, clear it
    if (!user && familyTreeForPreview) {
      setFamilyTreeForPreview(null);
    }
  }, [user, familyTreeForPreview]);

  const handleLogin = () => setShowAuth(true);
  const handleSignup = () => setShowAuth(true);

  // This function now handles form submission, AI call, DB save, and sets local preview
  const generateFamilyTree = async (formData: TreeFormData) => {
    if (!user || !session?.access_token) { // Check for session and token
      toast.error("Authentication required. Please log in to create a family tree.");
      setShowAuth(true);
      return;
    }

    setIsLoading(true);
    setFamilyTreeForPreview(null); // Clear previous preview

    // Use toast.promise for better UX during the multi-step async operation
    toast.promise(
      async () => {
        console.log("Submitting TreeFormData to Edge Function:", JSON.stringify(formData, null, 2));

        // Step 1: Call your Supabase Edge Function
        const edgeFunctionResponse = await supabase.functions.invoke("generate-family-tree", {
          body: formData, // Send the entire TreeFormData object
          // Supabase client's invoke should handle Authorization header if session is active
        });

        if (edgeFunctionResponse.error) {
          console.error("Edge Function invocation error:", edgeFunctionResponse.error);
          throw new Error(edgeFunctionResponse.error.message || "Failed to invoke AI generation service.");
        }
        
        const generatedData: {
          id: string; // This is the new tree_id generated by the Edge Function
          surname: string; tribe: string; clan: string;
          members: FamilyMember[]; source: 'ai' | 'fallback'; createdAt: string;
        } = edgeFunctionResponse.data;

        if (!generatedData || !generatedData.id || !generatedData.members) {
            console.error("Malformed response from Edge Function:", generatedData);
            throw new Error("Received incomplete or malformed data from AI generation service.");
        }

        console.log(`Data source from Edge Function: ${generatedData.source}`);
        if (generatedData.source === 'fallback') {
          toast.info("AI generation used fallback data. This will be saved.");
        } else {
          toast.success("Family tree structure processed by AI!");
        }

        // Step 2: Save the FamilyTree metadata to your 'family_trees' table
        const { data: savedTreeData, error: treeError } = await supabase
          .from('family_trees')
          .insert({
            id: generatedData.id, 
            user_id: user.id,
            surname: generatedData.surname,
            tribe: generatedData.tribe,
            clan: generatedData.clan,
            created_at: generatedData.createdAt, // Use timestamp from Edge Function
          })
          .select()
          .single();

        if (treeError) {
          console.error("Supabase tree insert error:", treeError);
          throw treeError;
        }
        if (!savedTreeData) throw new Error("Failed to save family tree metadata.");
        console.log("Family tree metadata saved:", savedTreeData);

        // Step 3: Save the FamilyMember records to your 'family_members' table
        if (generatedData.members && generatedData.members.length > 0) {
          const membersToInsert = generatedData.members.map(member => ({
            // Ensure mapping to snake_case for DB columns if they are snake_case
            id: member.id, name: member.name, relationship: member.relationship,
            birth_year: member.birthYear, death_year: member.deathYear,
            generation: member.generation, parent_id: member.parentId,
            is_elder: member.isElder, gender: member.gender, side: member.side,
            status: member.status, photo_url: member.photoUrl, notes: member.notes,
            family_tree_id: savedTreeData.id, 
            user_id: user.id,
          }));

          const { error: membersError } = await supabase
            .from('family_members')
            .insert(membersToInsert);

          if (membersError) {
            console.error("Supabase members insert error:", membersError);
            // Basic rollback: attempt to delete the tree metadata if members fail to save
            await supabase.from('family_trees').delete().eq('id', savedTreeData.id);
            throw membersError;
          }
          console.log(`${membersToInsert.length} family members saved.`);
        } else {
          console.warn("AI processed data but no members were returned/generated to save.");
          // Decide if saving an empty tree is okay or if this is an error condition
        }

        // Prepare the complete FamilyTree object for local preview
        const completeNewTreeForPreview: FamilyTree = {
          id: savedTreeData.id,
          userId: user.id,
          surname: savedTreeData.surname,
          tribe: savedTreeData.tribe,
          clan: savedTreeData.clan,
          createdAt: savedTreeData.created_at,
          members: generatedData.members || [], // Use members from AI for preview
        };
        setFamilyTreeForPreview(completeNewTreeForPreview);
        return completeNewTreeForPreview; // Return data for toast.promise success message
      },
      { // toast.promise messages
        loading: "Generating and saving your family tree...",
        success: (newTree) => `Family tree "${newTree?.surname}" created! Preview below.`,
        error: (err) => {
            // Check if err has a specific structure from Supabase or your own errors
            const message = err.details || err.message || "Unknown error during tree creation.";
            return `Operation failed: ${message}`;
        },
      }
    ).finally(() => {
        setIsLoading(false);
    });
  };

  const handleNavigateToTrees = () => {
    navigate('/family-trees'); // Navigate to your main list of saved trees
  };

  return (
    <div className="min-h-screen flex flex-col bg-background text-foreground">
      <Header onLogin={handleLogin} onSignup={handleSignup} />
      <main className="flex-grow">
        {/* Hero Section - YOUR EXISTING JSX - NO CHANGES */}
        <section className="py-16 px-4 bg-gradient-to-br from-uganda-black via-uganda-black to-uganda-red/90 text-white">
          <div className="container mx-auto max-w-7xl">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-center">
              <div>
                <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-4">
                  Discover Your <span className="text-uganda-yellow">Family Legacy</span>
                </h1>
                <p className="text-lg md:text-xl max-w-xl mb-6 text-gray-200">
                  Connect with your roots and preserve your Ugandan heritage by exploring your family tree through clan and tribal connections.
                </p>
                <div className="flex flex-wrap gap-4">
                  <Button 
                    className="bg-uganda-yellow hover:bg-uganda-yellow/90 text-uganda-black font-semibold px-6 py-3 rounded-lg"
                    onClick={() => document.getElementById('start-your-tree')?.scrollIntoView({ behavior: 'smooth' })}
                  >
                    Start Your Family Tree
                  </Button>
                  <Button 
                    variant="outline" 
                    className="border-white hover:bg-white/10 text-uganda-black font-bold bg-white px-6 py-3 rounded-lg"
                    onClick={() => navigate('/dna-test')}
                  >
                    <Dna className="h-4 w-4 mr-2" />
                    Get DNA Test
                  </Button>
                </div>
                <div className="mt-8 flex items-center gap-4">
                  <img 
                    src="https://upload.wikimedia.org/wikipedia/commons/3/3c/Download_on_the_App_Store_Badge.svg" 
                    alt="Download on App Store" 
                    className="h-10"
                  />
                  <img 
                    src="https://upload.wikimedia.org/wikipedia/commons/7/78/Google_Play_Store_badge_EN.svg" 
                    alt="Get it on Google Play" 
                    className="h-10"
                  />
                </div>
              </div>
              <div className="hidden lg:block"> {/* Your existing hero image placeholder */}
                <div className="relative">
                  <div className="w-full h-96 rounded-lg bg-gradient-to-br from-uganda-yellow/20 to-uganda-red/20 flex items-center justify-center">
                    <div className="w-32 h-32 rounded-full bg-uganda-yellow/30 border-4 border-uganda-yellow flex items-center justify-center">
                      <div className="text-center">
                        <p className="font-bold">Your Family</p>
                        <p className="text-sm">At the center</p>
                      </div>
                    </div>
                    {/* ... other decorative elements ... */}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        
        {/* Features Section - YOUR EXISTING JSX - NO CHANGES */}
        <section className="py-16 px-4 bg-card"> {/* Use theme variable bg-card */}
          <div className="container mx-auto max-w-7xl">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-bold mb-4 text-foreground"> {/* Use theme variable */}
                Discover Your Heritage with FamiRoots
              </h2>
              <p className="text-lg text-muted-foreground max-w-2xl mx-auto"> {/* Use theme variable */}
                Our powerful tools help you build, explore, and share your Ugandan family heritage
              </p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {/* Feature 1 */}
              <div className="bg-background p-6 rounded-lg shadow-md border-2 border-border hover:shadow-lg transition-shadow"> {/* Use theme variables */}
                <div className="w-16 h-16 bg-uganda-yellow rounded-full flex items-center justify-center mb-6">
                  <Users className="h-8 w-8 text-uganda-black" />
                </div>
                <h3 className="text-xl font-bold mb-3 text-foreground">Family Tree Builder</h3>
                <p className="text-muted-foreground mb-4">
                  Create your family tree centered around Ugandan clan structures, with AI assistance to build connections accurately.
                </p>
                <Button 
                  className="bg-uganda-red hover:bg-uganda-red/90 text-white w-full"
                  onClick={() => document.getElementById('start-your-tree')?.scrollIntoView({ behavior: 'smooth' })}
                >
                  Start Building
                </Button>
              </div>
              {/* Feature 2 & 3 - YOUR EXISTING JSX - NO CHANGES */}
              <div className="bg-background p-6 rounded-lg shadow-md border-2 border-border hover:shadow-lg transition-shadow"> {/* Use theme variables */}
                  <div className="w-16 h-16 bg-uganda-yellow rounded-full flex items-center justify-center mb-6">
                      <Dna className="h-8 w-8 text-uganda-black" />
                  </div>
                  <h3 className="text-xl font-bold mb-3 text-foreground">DNA Testing</h3>
                  <p className="text-muted-foreground mb-4">
                      Discover your ethnic origins and connect with relatives through our advanced genetic testing services.
                  </p>
                  <Button className="bg-uganda-red hover:bg-uganda-red/90 text-white w-full" onClick={() => navigate('/dna-test')}>
                      Explore DNA Testing
                  </Button>
              </div>
              <div className="bg-background p-6 rounded-lg shadow-md border-2 border-border hover:shadow-lg transition-shadow"> {/* Use theme variables */}
                  <div className="w-16 h-16 bg-uganda-yellow rounded-full flex items-center justify-center mb-6">
                      <Search className="h-8 w-8 text-uganda-black" />
                  </div>
                  <h3 className="text-xl font-bold mb-3 text-foreground">Relationship Analyzer</h3>
                  <p className="text-muted-foreground mb-4">
                      Find out how you're connected to other people through our powerful relationship detection tool.
                  </p>
                  <Button className="bg-uganda-red hover:bg-uganda-red/90 text-white w-full" onClick={() => navigate('/relationship-analyzer')}>
                      Analyze Relationships
                  </Button>
              </div>
            </div>
          </div>
        </section>

        {/* Form and Result Section */}
        <section id="start-your-tree" className="py-16 px-4 bg-background">
          <div className="container mx-auto max-w-7xl">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-bold mb-4 text-foreground">
                Start Your Family Tree Journey
              </h2>
              <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
                Enter your family information. Our AI will assist in structuring and generating your tree.
              </p>
            </div>
            
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
              {/* Form Column */}
              <div className="bg-card p-6 sm:p-8 rounded-xl shadow-xl border border-border">
                <FamilyTreeForm onSubmit={handleGenerateAndSaveTree} isLoading={isLoading} />
              </div>
              
              {/* Preview Column */}
              <div className="sticky top-24 self-start"> 
                <h3 className="text-2xl font-semibold mb-4 text-foreground text-center">
                  {familyTreeForPreview ? "Generated Tree Preview" : "Your Tree Will Appear Here"}
                </h3>
                {isLoading && !familyTreeForPreview && (
                    <div className="bg-card rounded-lg p-6 border-2 border-dashed border-border shadow-lg min-h-[550px] flex flex-col justify-center items-center">
                        <div className="animate-pulse flex flex-col items-center">
                            <Users className="h-16 w-16 text-uganda-yellow mb-4" />
                            <p className="text-muted-foreground">AI is building and saving your tree...</p>
                        </div>
                    </div>
                )}
                {!isLoading && familyTreeForPreview && (
                  <div className="bg-card rounded-lg shadow-xl border border-border overflow-hidden">
                    <div className="p-3 border-b border-border flex justify-between items-center bg-muted/30">
                        <p className="font-medium text-foreground text-sm">{familyTreeForPreview.surname} Family Tree</p>
                        <Button variant="outline" size="sm" onClick={handleNavigateToTrees} title="View all your saved trees">
                            <Eye className="mr-1.5 h-4 w-4"/> My Saved Trees
                        </Button>
                    </div>
                    {/* Scrollable container for FamilyTreeDisplay */}
                    <div className="h-[60vh] min-h-[500px] overflow-auto p-2 bg-background relative"> 
                      {/* This div applies the zoom for the preview on this Home page */}
                      <div style={{transform: `scale(${previewZoomLevel})`, transformOrigin: 'top left', width: 'fit-content', height: 'fit-content'}}>
                        <FamilyTreeDisplay 
                          tree={familyTreeForPreview} 
                          zoomLevel={1} // FamilyTreeDisplay's internal content uses zoomLevel 1 as parent div is scaled
                          // onTreeUpdate is not strictly needed here as edits on Home preview aren't saved back yet
                        />
                      </div>
                    </div>
                    <div className="p-2 border-t border-border flex justify-center gap-2 bg-muted/30">
                        <Button variant="outline" size="xs" onClick={() => setPreviewZoomLevel(z => Math.max(0.3, z - 0.1))} aria-label="Zoom Out Preview"><ZoomOut className="h-4 w-4"/></Button>
                        <Button variant="outline" size="xs" onClick={() => setPreviewZoomLevel(z => Math.min(1.5, z + 0.1))} aria-label="Zoom In Preview"><ZoomIn className="h-4 w-4"/></Button>
                         <Button variant="default" size="xs" className="bg-uganda-red text-white" onClick={handleNavigateToTrees}>
                            <Save className="mr-1.5 h-4 w-4"/> View My Saved Trees
                        </Button>
                    </div>
                  </div>
                )}
                {!isLoading && !familyTreeForPreview && ( /* Placeholder when not loading and no preview */
                  <div className="bg-card rounded-lg p-6 text-center border-2 border-dashed border-border shadow-lg min-h-[550px] flex flex-col justify-center items-center">
                    <div className="mb-4">
                        <div className="w-20 h-20 mx-auto mb-4 flex items-center justify-center rounded-full bg-uganda-yellow/20">
                            <FileText className="h-10 w-10 text-uganda-yellow" />
                        </div>
                        <h2 className="text-2xl font-bold mb-2 text-foreground">Your Family Tree</h2>
                        <p className="text-muted-foreground mb-6">
                            Fill out the form to generate and save your clan-based family tree.
                        </p>
                    </div>
                    {!user && ( /* Login/Signup prompt */
                        <div className="mt-6 p-4 bg-uganda-yellow/10 rounded-lg border border-uganda-yellow/30">
                            <p className="text-sm text-foreground">
                                <button onClick={handleLogin} className="text-uganda-red hover:underline font-medium">Login</button>
                                {" or "}
                                <button onClick={handleSignup} className="text-uganda-red hover:underline font-medium">Sign up</button>
                                {" to save your family tree."}
                            </p>
                        </div>
                    )}
                  </div>
                )}
              </div>
            </div>
          </div>
        </section>
        
        {/* Testimonials/Cultural Section - YOUR EXISTING JSX - NO CHANGES */}
        <section className="py-16 px-4 bg-gradient-to-br from-uganda-black to-uganda-black/90 text-white">
           {/* ... your existing testimonials content ... */}
           <div className="container mx-auto max-w-5xl text-center">
             <h2 className="text-3xl font-bold mb-8">Preserving Uganda's Rich Heritage</h2>
             {/* ... rest of content ... */}
           </div>
        </section>
      </main>
      <Footer />
      {showAuth && (<AuthForm onClose={() => setShowAuth(false)} />)}
    </div>
  );
};
export default Home;
