// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiqnkvmyfdbivxllmemc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppcW5rdm15ZmRiaXZ4bGxtZW1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDIxNzUsImV4cCI6MjA2MjE3ODE3NX0.nIvo9NPx3gpKvwxh18RAhmBbcffWUKJiUbsu5G4DQ2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);